certbot_create_certs: false
certbot_renew_certs_minute: 12,45
certbot_renew_certs_hour: 8
certbot_renew_certs_month: '*/1'
certbot_renew_certs_weekday: 1
certbot_waitfor_port_seconds: 3
certbot_webserver_installed: "nginx"
certbot_letsencrypt_version: "0.21.*"