mysql_backups_to_s3: false
tomcat_user: "tomcat7"
tomcat_group: "tomcat7"
openmrs_tomcat_http_port: 8081
openmrs_tomcat_shutdown_port: 8006
openmrs_tomcat_ajp_port: 8011
tomcat_https_port: 8443
openmrs_tomcat_max_filesize: "52428800"
openmrs_tomcat_fsize_threshold: "10485760"
openmrs_tomcat_version: 7
catalina_ops: "-Xms1500M -Xmx1500M"
openmrs_version: "2.1.4"
openmrs_validate_certs: true
openmrs_nginx_max_filesize: "50M"
openmrs_install_name: "openmrs"
openmrs_mysql_user: "openmrs"
openmrs_mysql_database: "openmrs"
openmrs_mysql_database_trigger: "openmrs_user_property"
openmrs_mysql_host: "localhost"
openmrs_mysql_app_host: "localhost"
openmrs_mysql_port: 3306
mysql_root_password: "root"
openmrs_mysql_password: "openmrs"
openmrs_dumps_gzipped: true
openmrs_dump_files: []
ssl_key: "{{ openmrs_site_name }}-key.pem"
ssl_cert: "{{ openmrs_site_name }}-fullchain.pem"
openmrs_system_user: "openmrs"
openmrs_system_group: "{{ tomcat_group }}"
openmrs_tomcat_instance: "tomcat-openmrs"
openmrs_tomcat_user_home: "/home/{{ openmrs_system_user }}"
openmrs_home_directory: "{{ openmrs_tomcat_user_home }}/.OpenMRS"
openmrs_mysql_connection_url: "jdbc:mysql://{{ openmrs_mysql_host }}:{{ openmrs_mysql_port }}/{{ openmrs_mysql_database }}?autoReconnect=true&sessionVariables=default_storage_engine=InnoDB&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull"
openmrs_mysql_root_user: "root"
openmrs_java_packages:
  - openjdk-8-jre
openmrs_admin_password:
openmrs_auto_update_database: "false"
openmrs_allow_web_admin: "true"
openmrs_encryption_vector:
openmrs_encryption_key:
openmrs_require_encryption: true
openmrs_binary_download_directory: "/tmp/openmrs_binary"
openmrs_binary_file_path: "{{ openmrs_binary_download_directory }}/{{ openmrs_install_name }}.war"
openmrs_log_level: "ERROR"

#OpenMRS modules
openmrs_modules:
  - "idgen-4.5.0"
  - "uiframework-3.13.0"
  - "registrationcore-1.8.0"
  - "providermanagement-2.10.0"
  - "teammodule-2.0.0B"
  - "uicommons-2.6.0"
  - "webservices.rest-2.24.0"
  - "legacyui-1.4.0"
  - "uilibrary-2.0.6"
  - "dhislocation-1.2.0"
  - "event-2.6.0"

# Hibernate
openmrs_hibernate_c3p0_min_size: 5
openmrs_hibernate_c3p0_timeout: 150
openmrs_hibernate_c3p0_idle_test_period: 120

# Swap
openmrs_swap_file_size_mb: 2048
openmrs_swap_swappiness: 10
openmrs_install_swap: false

# SSL
openmrs_ssl_src_dir: "/etc/letsencrypt/live/{{ openmrs_site_name }}"
openmrs_ssl_cert_file: "fullchain.pem"
openmrs_ssl_key_file: "privkey.pem"
openmrs_certs_from_letsencrypt: true
opensrp_certs_from_letsencrypt: true

openmrs_http_site: "{{ openmrs_site_name }}-http"
openmrs_https_site: "{{ openmrs_site_name }}-https"

# Certbot
openmrs_certbot_site_names: ["{{ openmrs_site_name }}"]
openmrs_certbot_mail_address: ""

# NGINX
openmrs_nginx_server_names_hash_bucket_size: 64
openmrs_nginx_sites:
  - server:
      name: "{{ openmrs_http_site }}"
      __listen: "80;\n  listen [::]:80;\n"
      server_name: "{{ openmrs_site_name }}"
      return: "301 https://$server_name$request_uri"
      ssl:
        enabled: false

  - server:
      name:  "{{ openmrs_https_site }}"
      __listen: "443;\n  listen [::]:443;\n"
      server_name: "{{ openmrs_site_name }}"
      client_max_body_size: "{{ openmrs_nginx_max_filesize }}"
      ssl:
        enabled: true
        cert: "{{ openmrs_ssl_cert_file }}"
        key:  "{{ openmrs_ssl_key_file }}"
        src_dir: "{{ openmrs_ssl_src_dir }}"
        conf: "{{ openmrs_site_name }}-ssl.conf"
        remote_src: "{{ openmrs_certs_from_letsencrypt }}"
        create_symlink: "{{ openmrs_certs_from_letsencrypt }}"
        access_log_format: "timed_combined"

      location1:
        name: "= /"
        return: "301 https://$host/{{ openmrs_install_name }}"

      location2:
        name: "/{{ openmrs_install_name }}"
        proxy_pass: "http://localhost:{{ openmrs_tomcat_http_port }}/{{ openmrs_install_name }}"
        proxy_read_timeout: "86400s"
        proxy_redirect: "off"
        proxy_next_upstream: "error timeout invalid_header http_502 http_503 http_504"
        proxy_set_header:
          - Host $host
          - X-Real-IP $remote_addr
          - X-Forwarded-For $proxy_add_x_forwarded_for
          - X-Forwarded-Host $server_name
          - X-Forwarded-Proto https
openmrs_nginx_log_dir: "/var/log/nginx"
openmrs_nginx_enabled_sites:
  - "{{ openmrs_http_site }}"
  - "{{ openmrs_https_site }}"
openmrs_nginx_disabled_sites:
  - default
openmrs_nginx_access_logs:
  - name: "timed_combined"
    format: "'$http_x_forwarded_for - $remote_user [$time_local]  \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" $request_time $upstream_response_time $gzip_ratio' $request_length"
    options: null
    filename: "access.log"

# Logstash
openmrs_install_logstash: false
openmrs_logstash_gelf_server: 127.0.0.1
openmrs_logstash_gelf_port: "12204"
openmrs_logstash_input_config_suffix: "{{ openmrs_site_name }}"
openmrs_clear_logstash_config: false
openmrs_logstash_plugins:
  - logstash-input-file
  - logstash-output-gelf
openmrs_logstash_custom_outputs:
  - output: 'gelf'
    lines:
      - 'host => "{{ openmrs_logstash_gelf_server }}"'
      - 'port => "{{ openmrs_logstash_gelf_port }}"'
      - 'sender => "%{host}"'
openmrs_logstash_custom_inputs:
  - input: 'file'
    lines:
      - 'path => ["{{ openmrs_nginx_log_dir }}/{{ openmrs_https_site }}-ssl-access.log"]'
      - 'start_position => "end"'
      - 'add_field => {'
      - '  ssl => true'
      - '  nginx_access => true'
      - '  from_nginx => true'
      - '  from_host => "%{host}"'
      - '  from_domain => "{{ openmrs_site_name }}"'
      - '  from_{{ openmrs_system_user }} => true'
      - '  git_version => "{{ openmrs_version }}"'
      - '}'

#Logstash
openmrs_collectd_version: "5.5.*"