certbot_crt: "{{ certbot_fqdn_home }}/cert.pem"
certbot_key: "{{ certbot_fqdn_home }}/privkey.pem"
certbot_fqdn_home: "{{ certbot_live_home }}/{{ site_name }}"
certbot_chain: "{{ certbot_fqdn_home }}/chain.pem"
certbot_fullchain: "{{ certbot_fqdn_home }}/fullchain.pem"
certbot_live_home: /etc/letsencrypt/live
