---
- include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: Stop webserver
  service:
    name: "{{ certbot_webserver_installed }}"
    state: stopped

- name: Check whether port 80 is available
  wait_for:
    port: 80
    state: stopped
    timeout: "{{ certbot_waitfor_port_seconds }}"

- name: Create certs
  command: letsencrypt certonly --standalone -d {{ site_name }} -m {{ certbot_mail_address }} --agree-tos --noninteractive --text
  args:
    creates: "{{ certbot_crt }}"
  when: certbot_create_certs

- include_tasks: copy-files.yml

- name: Renew certs every month
  cron:
    name: renewCertbotCerts
    minute: "{{ certbot_renew_certs_minute }}"
    hour: "{{ certbot_renew_certs_hour }}"
    month: "{{ certbot_renew_certs_month }}"
    weekday: "{{ certbot_renew_certs_weekday }}"
    job: /usr/bin/letsencrypt renew
  when: certbot_create_certs

- name: Start webserver
  service:
    name: "{{ certbot_webserver_installed }}"
    state: started
