---
- hosts: monitoring_graphite
  gather_facts: false
  become: true
  collections:
    - onaio.monitoring
  pre_tasks:
    - name: load in monitoring vars
      include_vars:
        file: "vars/{{ monitoring_setup_type }}.yml"
    - include_tasks: tasks/python3-ubuntu.yml
    - name: Setup Ansible
      setup:
  roles:
    - role: onaio.monitoring.graphite
