---
- hosts: monitoring_graylog
  gather_facts: false
  become: true
  collections:
    - onaio.monitoring
  pre_tasks:
    - name: load in monitoring vars
      include_vars:
        file: "vars/{{ monitoring_setup_type }}.yml"
    - include_tasks: tasks/python3-ubuntu.yml
    - name: Setup Ansible
      setup:
  roles:
    - role: onaio.monitoring.java
      java_home: "/usr/lib/jvm/java-8-openjdk-amd64/jre"
      java_packages:
        - openjdk-8-jdk

    - role: "Graylog2.graylog-ansible-role"

    - role: onaio.monitoring.certbot

    - role: onaio.monitoring.nginx
