---
mysql_install_server: true
mysql_client_version: "5.7*"
mysql_server_version: "5.7*"
mysql_python_mysqldb_version: "1.3.*"
mysql_setup_database_backups: true
mysql_port: 3306
mysql_bind_address: 127.0.0.1
mysql_backup_connection_host: "127.0.0.1"
mysql_root_user: "root"
mysql_root_password:
mysql_root_user_allowed_host_regex: "{{ mysql_bind_address }}"

mysql_collectd_version: "5.5.*"