---
- name: Ensures {{ opensrp_user_home }}/.postgresql dir exists
  become: yes
  become_user: root
  file: path="{{ opensrp_user_home }}/.postgresql"
    state=directory

- name: Download Postgres CA certificate bundle
  become: yes
  become_user: root
  copy:
    content: "{{ opensrp_postgres_ca_bundle_content }}"
    dest: "/usr/local/share/ca-certificates/postgres-ca-bundle.crt"
    force: yes
  register: downloaded_ca_bundle
  when: opensrp_postgres_ca_bundle_content|length > 0

- name: Update Postgres CA certificates
  become: yes
  become_user: root
  command: "update-ca-certificates"
  when: (opensrp_postgres_ca_bundle_content|length > 0 and downloaded_ca_bundle is changed)

- name: Copy the Postgres CA certificate bundle to postgres default location
  become: yes
  become_user: root
  copy:
    src: "/usr/local/share/ca-certificates/postgres-ca-bundle.crt"
    dest: "{{ opensrp_user_home }}/.postgresql/root.crt"
    remote_src: yes
  when: opensrp_postgres_ca_bundle_content|length > 0

- name: Install migration prerequisites
  become: yes
  become_user: "root"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - unzip
    - python-migrate
    - postgresql
    - libpq-dev
    - python3-psycopg2
    - git
  tags:
    - postgresql

- name: Ensure checkout directory is empty
  become: yes
  file:
    state: absent
    path: "{{ opensrp_remote_checkout_path }}"
  tags:
    - postgresql

- name: Checking out codebase
  become: yes
  git:
    repo: "{{ opensrp_git_url }}"
    dest: "{{ opensrp_remote_checkout_path }}"
    version: "{{ opensrp_version }}"
    recursive: yes
  tags:
    - postgresql


- name: Copy the OpenSRP migrations environment configs
  become: yes
  template:
    src: "templates/opensrp_remote_checkout_path/configs/assets/migrations/environments/opensrp_mybatis_env.properties.j2"
    dest: "{{ opensrp_remote_checkout_path }}/configs/assets/migrations/environments/{{ opensrp_mybatis_env }}.properties"
  tags:
    - postgresql

- name: Make codebase readable
  become: yes
  file:
    path: "{{ opensrp_remote_checkout_path }}"
    mode: "0755"

- name: Make sure the OpenSRP PostgreSQL database exists
  postgresql_db:
    name: "{{ opensrp_postgresql_database }}"
    login_host: "{{ opensrp_postgres_host }}"
    port: "{{ opensrp_postgres_port }}"
    login_user: "{{ opensrp_postgres_superuser }}"
    login_password: "{{ opensrp_postgres_superuser_password }}"
  when: not opensrp_install_only
  tags:
    - postgresql

- name: Ensure OpenSRP psql user has the right access level
  postgresql_user:
    db: "{{ opensrp_postgresql_database }}"
    login_host: "{{ opensrp_postgres_host }}"
    port: "{{ opensrp_postgres_port }}"
    login_user: "{{ opensrp_postgres_superuser }}"
    login_password: "{{ opensrp_postgres_superuser_password }}"
    name: "{{ opensrp_postgresql_user }}"
    password: "{{ opensrp_postgresql_password }}"
    encrypted: yes
    priv: ALL
    role_attr_flags: "{{ opensrp_postgresql_user_role_attr_flags }}"
  when: not opensrp_install_only
  tags:
    - postgresql

- name: Make sure the Mybatis installation dir exists
  become: yes
  become_user: "root"
  file:
    path: "{{ opensrp_mybatis_install_dir }}"
    state: "directory"
    owner: "{{ ansible_ssh_user }}"
    mode: "0755"
  tags:
    - postgresql

- name: Download the Mybatis archive
  unarchive:
    src: "https://github.com/mybatis/migrations/releases/download/mybatis-migrations-{{ opensrp_mybatis_version }}/mybatis-migrations-{{ opensrp_mybatis_version }}-bundle.zip" # noqa 204
    dest: "{{ opensrp_mybatis_install_dir }}"
    remote_src: yes
  tags:
    - postgresql

- name: Run the Mybatis migrations # noqa 301
  command: "{{ opensrp_mybatis_install_dir }}/mybatis-migrations-{{ opensrp_mybatis_version }}/bin/migrate up --path={{ opensrp_remote_checkout_path }}/configs/assets/migrations --env={{ opensrp_mybatis_env }} {{ opensrp_mybatis_migration_extra_args }}" # noqa 204
  when: not opensrp_install_only
  tags:
    - postgresql

- name: Ensure checkout directory is empty
  become: yes
  file:
    state: absent
    path: "{{ opensrp_remote_checkout_path }}"
  when: not opensrp_install_only
  tags:
    - postgresql
